# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathema', '0005_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('content', models.TextField(default='Dica')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mathema.Activity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathema.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSuport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mathema.Suport')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathema.Topic')),
            ],
        ),
        migrations.RenameModel(
            old_name='TipoSuporte',
            new_name='ActivityType',
        ),
        migrations.RenameModel(
            old_name='Objetivo',
            new_name='Objective',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='atividades',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='suportes',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='topicoPai',
        ),
        migrations.RemoveField(
            model_name='topicoatividade',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='topicoatividade',
            name='topico',
        ),
        migrations.RemoveField(
            model_name='topicosuporte',
            name='suporte',
        ),
        migrations.RemoveField(
            model_name='topicosuporte',
            name='topico',
        ),
        migrations.RenameField(
            model_name='activitytype',
            old_name='nome',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='data_criacao',
            new_name='creation_data',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='descricao',
        ),
        migrations.AddField(
            model_name='answer',
            name='evaluation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objective',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathema.Activity'),
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Suporte',
        ),
        migrations.DeleteModel(
            name='Topico',
        ),
        migrations.DeleteModel(
            name='TopicoAtividade',
        ),
        migrations.DeleteModel(
            name='TopicoSuporte',
        ),
        migrations.AddField(
            model_name='topic',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, through='mathema.TopicActivity', to='mathema.Activity'),
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mathema.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='supports',
            field=models.ManyToManyField(blank=True, null=True, through='mathema.TopicSuport', to='mathema.Suport'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mathema.ActivityType'),
        ),
    ]
