# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathema', '0006_auto_20180206_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('content', models.TextField(default='Dica')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathema.Support')),
            ],
        ),
        migrations.RemoveField(
            model_name='suport',
            name='author',
        ),
        migrations.RemoveField(
            model_name='topicsuport',
            name='support',
        ),
        migrations.RemoveField(
            model_name='topicsuport',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='supports',
        ),
        migrations.AddField(
            model_name='activity',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, through='mathema.TopicActivity', to='mathema.Topic'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='activity_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'problemas'), (2, 'multipla escolha')], default=1),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topicactivity',
            name='activity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mathema.Activity'),
        ),
        migrations.DeleteModel(
            name='Suport',
        ),
        migrations.DeleteModel(
            name='TopicSuport',
        ),
        migrations.AddField(
            model_name='topicsupport',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathema.Topic'),
        ),
        migrations.AddField(
            model_name='topiccurriculum',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathema.Curriculum'),
        ),
        migrations.AddField(
            model_name='topiccurriculum',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathema.Topic'),
        ),
        migrations.AddField(
            model_name='support',
            name='topics',
            field=models.ManyToManyField(blank=True, through='mathema.TopicSupport', to='mathema.Topic'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, through='mathema.TopicCurriculum', to='mathema.Topic'),
        ),
    ]
